import { FetchProvider } from "./context/AuthContext";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <FetchProvider>
      <body>{children}</body>
      </FetchProvider>
    </html>
  );
}
